<?php

namespace Database\Seeders;

use App\Models\SiteWalkDown\Dropdown as SiteWalkDownDropdown;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ApplicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SiteWalkDownDropdown::insert([
            [ 'title' => 'Acid Gas Removal', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Boil-off Gas Compressor Anti-surge', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Booster Pump Recirculation', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Brine Disposal Flow Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Brine Injection Pump Min Flow Recirculation Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Brine Storage Tank Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Bulk Treater Oil Out', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Bulk Treater Produced Water', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Butane Pump Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Butane to Product Meter Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Cavern Injection Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Cavern Withdrawal Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Chemical Injection', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Cold Joule-Thomson', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Compression Suction Scrubber Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Compression Suction Throttle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Compressor Anti-surge', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Compressor Export Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Condensate Product Meter Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Crude Oil Discharge', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Debutanizer Bottoms Pump Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Debutanizer Reboiler Hot Oil Return Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Debutanizer Reflux Pump Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Debutanizer Reflux Pump to Debutanizer Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Deethanizer Inlet Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Deethanizer Reboiler Hot Oil Return Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Deethanizer Reboiler to Depropanizer Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Deethanizer Reflux Pump Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Deethanizer Reflux Pump to Deethanizer Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Delivery Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Depropanizer Bottom Reboiler Hot Oil Return Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Depropanizer Bottom Reboiler to Debutanizer Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Depropanizer Heat Pump Compressor Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Depropanizer Heat Pump Compressor to Deethanizer Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Depropanizer Heat Pump Compressor to Depropanizer Side Reboiler', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Depropanizer Heat Pump Compressor to Reflux Accumulator Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Dry Oil Pump Recirculation', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Electrostatic Treater Oil Out', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Electrostatic Treater Produced Water', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Ethane Booster Pump Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Ethane Pump Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Ethane to Product Meter Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Export Compressor Anti-Surge Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Feed Gas Inlet Pressure Letdown', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Feedwater Injection Pump Discharge Maximum Flow Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'First Stage Compression Suction Scrubber Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'First Stage Compressor Antisurge and/or Recycle', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'First Stage Discharge Cooler Temperature Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Flash Drum Lean Solvent Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Flash Drum Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Flash Drum Pressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Flash Drum Water Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Flash Gas to Flare Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Flow Balancing Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Fourth Stage Compression Suction Scrubber Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Fourth Stage Compressor Antisurge and/or Recycle', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Fourth Stage Discharge Cooler Temperature Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Free Acid Gas Drum Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Fuel Gas System', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Gas Dehydration Inlet Separator Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Gas Outlet Back Pressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Glycol Contactor Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Heat Exchanger Temperature Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Heat Transfer Fluid Inlet to Heater', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'High Pressure Separator Gas Outlet Pressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'High Pressure Separator Oil Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'High Pressure Separator Vent to Flare', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'High Pressure Separator Water Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Hot Gas Bypass', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'HP Flare Scrubber', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Injection Compressor Anti-surge Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Intermediate Pressure Separator Gas Outlet Pressure Control:', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Intermediate Pressure Separator Oil Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Intermediate Pressure Separator Vent to Flare', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Intermediate Pressure Separator Water Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Amine Booster Pump Recirculation Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Amine Flow Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Amine Main Pump Recirculation Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Amine to Contactor Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Amine to Tail Gas Absorber Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Gas Separator Level', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Gas Separator Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Gas Separator Sour Water Letdown Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Gas to Flare Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Lean Glycol to Glycol Contactor Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'LNG Temperature', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'LNG Unloading Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Low Pressure Separator Gas Outlet Pressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Low Pressure Separator Oil Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Low Pressure Separator Vent to Flare', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Low Pressure Separator Water Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'LP Separator Oil Interface Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'LP Separator Produced Water Interface Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Manifold Flow Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Manifold Pressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Meter Backpressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Propane Pump Recycle Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Propane to Product Meter Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Pump Discharge', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Refrigerant Cycles', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Regeneration Lean Amine Pump Recirculation Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Rich Amine Letdown Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Rich Amine Pump Discharge to Regeneration Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Rich Amine Recirculation to Acid Gas Enrichment Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Second Stage Compression Suction Scrubber Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Second Stage Compressor Antisurge and/or Recycle', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Second Stage Discharge Cooler Temperature Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Send-out Pump Recirculation', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Separator Inlet Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Slug Catcher Gas to Flare', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Slug Catcher Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Slug Catcher to Test Separator Heating Medium Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Tail Gas Knockout Drum Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Tail Gas Quench Water Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Tail Gas Treater Semi-lean Amine Letdown Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Tank Fill Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Test Separator Gas Outlet Pressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Test Separator Produced Water Interface Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Third Stage Compression Suction Scrubber Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Third Stage Compressor Antisurge and/or Recycle', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Third Stage Discharge Cooler Temperature Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Vapor Return Line Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Vaporizer Inlet Flow Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Warm Joule-Thomson', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Water Injection', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Water Injection Discharge Pressure Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Water Injection Pump Minimum Flow Recirculation Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Water Injection Pump Recirculation', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Water Injection Surge Vessel Level Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Water Injection System Control', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Water Treatment', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
            [ 'title' => 'Wellsite Choke', 'alias' => 'DVCAPP', 'device_type' => null, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now() ],
        ]);
    }
}
