<?php

namespace Database\Seeders;

use App\Models\SiteWalkDown\DeviceType;
use App\Models\SiteWalkDown\PotensialCauseOption;
use App\Models\SiteWalkDown\ValveConditionSubject;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PotensialCauseOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* Get device types & convert it into collection */
        $deviceTypes = DeviceType::select('id','initial')->get();
        $deviceType = collect();
        foreach ($deviceTypes as $value) {
            $deviceType->put($value->id, $value->initial);
        }

        $potensialCauseOptions = [
            /* Control Valve - COV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Corrosion'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Vibration'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cavitation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Corrosion'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Flashing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Overthrust/torque'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Process Requirement/Technician Qualification'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Vibration'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Corrosion'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Galvanic Corrosion'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Protective Coating'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Corrosion'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Out of Calibration'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Process Requirement/Technician Qualification'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Erroded'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Corroded'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Corroded'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Operational'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Corroded'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lifetime'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'None'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Out of Calibration'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Out of Specification'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Wrong/Missed Installation'],
            /* Regulator Valve - REG */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Corroded'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Corrosion'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Lifetime'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'None'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Record Data Failed'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Technician Qualification'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Vibration'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Galvanic Corrosion'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Lifetime'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'None'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong/Missed Protective Coating'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong/Missed Sizing and Selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Corroded'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Corrosion'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Lifetime'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'None'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Record Data Failed'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Technician Qualification'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Unlisenced Calibration'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Vibration'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Corroded'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Corrosion'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Lifetime'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'None'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Record Data Failed'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Technician Qualification'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Unlisenced Calibration'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Vibration'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Corroded'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Lifetime'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'None'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Wrong/Missed Operational'],
            /* Check Valve - CKV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Corrosion'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Lifetime'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'None'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Galvanic Corrosion'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Lifetime'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'None'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong/Missed Protective Coating'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong/Missed Sizing and Selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Corrosion'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Lifetime'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'None'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Process Requirement/Technician Qualification'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Vibration'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Lifetime'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'None'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Process Requirement/Technician Qualification'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Vibration'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Corroded'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Lifetime'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'None'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Wrong/Missed Operational'],
            /* Isolation Valve - ISV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corrosion'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corrosion'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Vibration'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Vibration'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cavitation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corrosion'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Flashing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Overthrust/torque'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Process Requirement/Technician Qualification'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Vibration'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corrosion'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Galvanic Corrosion'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Protective Coating'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corrosion'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Out of Calibration'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Process Requirement/Technician Qualification'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Erroded'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corroded'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corroded'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Operational'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Corroded'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lifetime'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'None'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Out of Calibration'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Out of Specification'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Wrong/Missed Installation'],
            /* Pressure Relieve Valve - PRV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Corroded'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Corrosion'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Lifetime'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'None'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Record Data Failed'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Vibration'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Corroded'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Corrosion'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Lifetime'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'None'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Record Data Failed'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Unlisenced Calibration'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Vibration'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Galvanic Corrosion'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Lifetime'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'None'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong/Missed Protective Coating'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'None'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Corroded'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Corrosion'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Lifetime'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Record Data Failed'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Unlisenced Calibration'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Vibration'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Corroded'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Lifetime'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'None'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Wrong/Missed Operational'],
            /* Manual Valve - MAV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Corrosion'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Corrosion'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Vibration'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Vibration'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve product selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Inaccurate valve sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cavitation'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Corrosion'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Flashing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Overthrust/torque'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Process Requirement/Technician Qualification'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Vibration'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong material selection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Galvanic Corrosion'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Protective Coating'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Corroded'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Technician Qualification'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Installation'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Corroded'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lifetime'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'None'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Overtorque/Thurst'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong Sizing/Selection'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Lubrication'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Wrong/Missed Operational'],
        ];

        foreach ($potensialCauseOptions as $potensialCauseOption) {
            $valveConditionSubjects = ValveConditionSubject::select('id')
                ->where([
                    ['device_type_id', '=', $potensialCauseOption['deviceType']],
                    ['code', '=', $potensialCauseOption['id']],
                ])->first();

            PotensialCauseOption::insert([
                'device_type_id' => $potensialCauseOption['deviceType'],
                'valve_condition_subject_id' => $valveConditionSubjects->id,
                'title' => $potensialCauseOption['title'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
