<?php

namespace Database\Seeders;

use App\Models\SiteWalkDown\DeviceType;
use App\Models\SiteWalkDown\RecommendationOption;
use App\Models\SiteWalkDown\ValveConditionSubject;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RecommendationOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* Get device types (PRV, CKV, COV) & convert it into collection */
        $deviceTypes = DeviceType::select('id','initial')->get();
        $deviceType = collect();
        foreach ($deviceTypes as $value) {
            $deviceType->put($value->id, $value->initial);
        }

        $recommendationOtions = [
            /* Control Valve - COV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lubrication'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Packing Flange/Gland Tightening'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('COV'), 'title' => 'Upgrade material'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('COV'), 'title' => 'Upgrade material'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'NDE'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Support'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('COV'), 'title' => 'Upgrade material'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'NDE'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Sealant Injection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Coating'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-Install'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-Sizing'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Calibration'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Hydraulic Oil Replacement'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lubrication'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Support'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lubrication'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lubrication'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Painting'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Lubrication'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Painting'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Repair'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('COV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Calibration'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Cleaning'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Regular valve assesment'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Replace'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('COV'), 'title' => 'Re-sizing'],
            /* Regulator - REG */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Calibration'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Cleaning'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Open and Inspect'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Painting/Coating'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Repair'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Replace'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Re-sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('REG'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Cleaning'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Coating'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Re-Install'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Replace'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('REG'), 'title' => 'Re-Sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Calibration'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Cleaning'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Open and Inspect'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Painting/Coating'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Repair'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Replace'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Re-sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('REG'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Calibration'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Cleaning'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Open and Inspect'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Painting/Coating'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Repair'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Replace'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Re-sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('REG'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Cleaning'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Lubrication'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Open and Inspect'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Painting'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Repair'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Replace'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Re-sizing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('REG'), 'title' => 'Technician Training and Development'],
            /* Check Valve - CKV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Cleaning'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Lubrication'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Packing Flange/Gland Tightening'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Repair'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Replace'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Re-sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Upgrade material'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Cleaning'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Coating'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Re-Install'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Replace'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Re-Sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Bolt/Joint Tightening'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Cleaning'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Repair'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Replace'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Re-sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Cleaning'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Repair'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Replace'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Re-sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Cleaning'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Lubrication'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Painting'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Repair'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Replace'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Re-sizing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('CKV'), 'title' => 'Technician Training and Development'],
            /* Isolation Valve - ISV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lubrication'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Packing Flange/Gland Tightening'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Upgrade material'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Bolt/Joint Tightening'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Upgrade material'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Upgrade material'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'NDE'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Support'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Upgrade material'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'NDE'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Sealant Injection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Coating'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-Install'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-Sizing'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Calibration'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Hydraulic Oil Replacement'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lubrication'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Support'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lubrication'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS9', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lubrication'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Painting'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS10', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Lubrication'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Painting'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Repair'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            ['id' => 'AS11', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Calibration'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Cleaning'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Regular valve assesment'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Replace'],
            ['id' => 'AS12', 'deviceType' => $deviceType->search('ISV'), 'title' => 'Re-sizing'],
            /* Pressure Relief Valve - PRV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Calibration'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Cleaning'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Repair'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Replace'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Re-sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Upgrade material'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Calibration'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Cleaning'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Repair'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Replace'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Re-sizing'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Cleaning'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Coating'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Re-Install'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Replace'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Re-Sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Calibration'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Cleaning'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Repair'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Replace'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Re-sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Cleaning'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Lubrication'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Painting'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Repair'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Replace'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Re-sizing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('PRV'), 'title' => 'Technician Training and Development'],
            /* Manual Valve - MAV */
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lubrication'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Packing Flange/Gland Tightening'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Repair'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-sizing'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS1', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Upgrade material'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Bolt/Joint Tightening'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Repair'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-sizing'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS2', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Upgrade material'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Bolt Joint Tightening'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Joint surface inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Repair'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-sizing'],
            ['id' => 'AS3', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Upgrade material'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'NDE'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Painting/Coating'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Repair'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace with correct material'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace/upgrade product'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-sizing'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Support'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS4', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Upgrade material'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'NDE'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Repair'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-sizing'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Sealant Injection'],
            ['id' => 'AS5', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Coating'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-Install'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS6', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-Sizing'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lubrication'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Painting'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Repair'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-sizing'],
            ['id' => 'AS7', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Technician Training and Development'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Cleaning'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Lubrication'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Open and Inspect'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Painting'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Regular Monitoring and Inspection'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Repair'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Replace'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Re-sizing'],
            ['id' => 'AS8', 'deviceType' => $deviceType->search('MAV'), 'title' => 'Technician Training and Development'],
        ];

        foreach ($recommendationOtions as $recommendationOption) {
            $valveConditionSubjects = ValveConditionSubject::select('id')
                ->where([
                    ['device_type_id', '=', $recommendationOption['deviceType']],
                    ['code', '=', $recommendationOption['id']],
                ])->first();

            RecommendationOption::insert([
                'device_type_id' => $recommendationOption['deviceType'],
                'valve_condition_subject_id' => $valveConditionSubjects->id,
                'title' => $recommendationOption['title'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
